### ISSUE TITLE
Second Account (CreditCard) is not detected for DKB

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#11]
Hi, 

i have tested the app with DKB. I have a Giro which is displayed just fine. However i do also
have a credit card there -> which is also properly provided, but for some reason the Account
does not show up in the UI - could you check why it is not showing up or is only one account per
bank possible (what also is strange is the following message : NOT a real account...   maybe
that is the problem. Here is the log for the seccond account (anonymized) - if you need more infos,
please tell me. 

ec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] === Found account! ===
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account ID:  "499897007XXXXXXX"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Bank ID:  "1203XXXX"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] IBAN:  ""
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] User ID:  "87312XXXXX"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Kind:  "50"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Currency:  "EUR"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Owner 1:  "XXXXXXXXXXXX"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Owner 2:  ""
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Description:  "VISA DKB Cash"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Account Limit:  ""
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKSAK"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKISA"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKSSP"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKPAE"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKTAZ"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKTLA"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKTSP"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKTLF"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKPSA"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKPSP"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "HKTAN"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKANA"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKANL"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKKAU"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKKKA"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKKKS"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] Allowed Transaction:  "DKKKU"
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] NOT a real account...
Dec 06 22:58:09 Sailfish [29445]: [D] unknown:0 - [FinTsDialog] New Customer System ID:  "YsDIDTNxhWcBAABNLCWXslkXrAQA"

**Comment by Wunderfitz** [comment]
Please see issue #8. Therefore closing this one as duplicate.
