### ISSUE TITLE
Consors accounts cannot be fetched

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#12]
Hi, i cannot fetch my consors accounts. I am sure i have entered the PIN correct. however i am always getting the following response :

Dec 09 12:41:10 Sailfish [28319]: [D] unknown:0 - FinTsDialog::searchInstitute "Consors"
Dec 09 12:41:10 Sailfish [28319]: [D] unknown:0 - FinTsDialog::handleInstitutesSearchCompleted "Consors"
Dec 09 12:41:11 Sailfish [28319]: [D] onClicked:116 - Selected: BNP Paribas S.A. Niederlassung Deutschland-Consorsbank, 70120400, https://brokerage-hbci.consorsbank.de/hbci
Dec 09 12:41:11 Sailfish [28319]: [D] unknown:0 - FinTsDialog::initializeParameters
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::synchronization
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createMessageSynchronization
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HKIDN" "3" "2"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HKVVB" "4" "3"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HKSYN" "5" "3"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHA" "6" "2"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBS" "7" "1"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSK" "998" "3"
Dec 09 12:41:41 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSD" "999" "1"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::handleSynchronizationFinished
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::parseReplyDialogInitialization
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsDialog] Bank told us to use dialog ID "0000044IP1SKAPG8HPVQ8J2QUOSUBG"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsDialog] Feedback for message:  "9800" "Der Dialog wurde abgebrochen."
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsDialog] Feedback for message:  "9942" "PIN ungültig."
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::closeDialog
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createMessageCloseDialog
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HKEND" "3" "1"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHA" "4" "2"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBS" "5" "1"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSK" "998" "3"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSD" "999" "1"
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::handleDialogEndFinished
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsDialog::parseReplyCloseDialog
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsDialog] Feedback for message:  "9800" "Der Dialog wurde abgebrochen."
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsDialog] Feedback for message:  "9120" "Dialog bereits beendet oder abgebrochen. Bitte melden Sie sich erneut an."
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - FinTsBalances::retrieveBalances
Dec 09 12:41:58 Sailfish [28319]: [D] unknown:0 - [FinTsBalances] No accounts found, no balances will be retrieved!

**Comment by Wunderfitz** [comment]
I'm terribly sorry, but I can't do anything if the bank says "PIN invalid". Please check with your bank if you need to use a different username/password combination. You can also try using Hibiscus https://www.willuhn.de/products/hibiscus/ with your credentials. If this one works with the these ones, we can dig deeper... Until then, I close this ticket.
