### ISSUE TITLE
Feature-Request: Multiple Accounts

### ISSUE THREAD

**Issue by jsaalfeld** [Wunderfitz/harbour-zaster#15]
I tested the App multiple weeks ago, shortly after Release and was about to use it "productively", but I didn't find any options to add multiple accounts (like one from Sparkasse and another one from Volksbank).

I'm either not able to find the option to add multiple accounts or the feature is missing (hence the title).

**Comment by Wunderfitz** [comment]
Please update to version 0.2 It supports multiple accounts via the Settings menu.
