### ISSUE TITLE
Removing Accounts results in blank page

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#17]
Hi,

i do not know if the error occurs if you start with now account, but anyway.
I have two accounts and want to add a third.

Start with "Login with other Account" -> Search for e.g. "Consors" -> select one
of the three. The enter some invalid credentials (wrong user / password). and select "Login"
You will get an error message. click ok. You will get to a dialog that show a "Remove this account" 
button at the bottom. click on the button. The you get a blank screen, with no way of
any interaction (no pully or back whatsoever). you have to close the app and restart it. to be able to
do anything.

**Comment by Wunderfitz** [comment]
Thanks for the report. Will tackle that in one of the next releases.
