### ISSUE TITLE
Stuck in bank selection - if you do not add account.

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#18]
Hi,

Start with "Login with other Account" -> Search for e.g. "Consors". Now you can select a bank account
however, there is no way of cancelling the add process, you can only continue. if you do not want to 
add an account for example because you did not find your's you have to quit the app, or add a random
one that you remove later. If you kill the app and restart it, you are back to the bank selection
dialog without a possibility to go back. basically you are stuck and you have to add a dummy account
to be able to go back to the account selection / normal account login. The question is why restarting
the app brings you back the the account selectin dialog? and why is it not possible to cancel it?

**Comment by Wunderfitz** [comment]
Well, it's simply implemented that way - obviously slightly buggy in this case... There was no intention of bringing the app into an inconsistent state. If there is no way out, please delete /home/nemo/.config/harbour-zaster and restart the app. I'll see when I can fix that...
