### ISSUE TITLE
Login to 1822direkt fails

### ISSUE THREAD

**Issue by ziel-los** [Wunderfitz/harbour-zaster#3]
Tried to open my 1822direkt account. First, the search gives the wrong BLZ 50050222 instead of 50050201. When trying to access Frankfurter Sparkasse (which is 1822 is a part of) the correct BLZ is given. 
<p>First attempt (wrong BLZ 50050201) gives error numbers 9050 and 9210. Second attempt (correct BLZ 50050201) causes app to crash.

**Comment by Wunderfitz** [comment]
Thanks for the report. Please always use the BLZ if you have doubts. For the crash, I need logs. Could you please start the app 'harbour-zaster' from the Terminal and send me the output? Please see https://together.jolla.com/question/103763/how-to-start-an-app-from-terminal-and-collect-log/ for details how to do that.

**Comment by ziel-los** [comment]
[D] unknown:0 - Using Wayland-EGL
[D] unknown:0 - Initializing Wagnis...
[D] unknown:0 - Wagnis::getIpInfo
[D] unknown:0 - "No carrier"
[D] unknown:0 - [Wagnis] We found IMEI(s). "1"
[D] unknown:0 - [Wagnis] Using IMEI for the ID "358098072012992"
[D] unknown:0 - [Wagnis] Using Wi-Fi MAC address for the ID "58:48:22:a4:06:68"
[D] unknown:0 - [Wagnis] Complete hash:  "37dec96515cafdc8c173fb8145d13b83393218bce0d8e13f789028849efe1644"
[D] unknown:0 - [Wagnis] ID:  "37de-c965-15ca-fdc8"
[D] unknown:0 - Wagnis::readRegistration
[D] unknown:0 - FinTsDialog::initializeParameters
[D] unknown:0 - Institutes database: Connection OK
[D] unknown:0 - "Using encryption key: 285183ef-c2ab-4f32-9b79-1d7cda9f12e0"
[W] unknown:0 - QString::arg: Argument missing: Zaster Banker ist und wird Open Source-Software bleiben. Allerdings bitte ich Sie um einen Beitrag für die Unterstützung der Entwicklung von Zaster Banker, bevor sie die Anwendung ausführen können. Solch ein Beitrag kann geleistet werden, indem Sie Zaster Banker in eine andere Sprache übersetzen, bei der Entwicklung mithelfen, oder indem Sie einen Schlüssel erwerben., Zaster Banker
[D] unknown:0 - Wagnis::handleGetIpInfoFinished
[D] unknown:0 - [Wagnis] Country:  "DE"
[D] unknown:0 - Wagnis::registerApplication
[D] unknown:0 - Wagnis::getRegistrationDocument
[W] unknown:0 - Wagnis::handleRegisterApplicationError: 206 "Error transferring https://werkwolf.eu/wagnis/v1/registration.php - server replied: Conflict" ""
[D] unknown:0 - [Wagnis] Installation already registered!
[D] unknown:0 - Wagnis::getApplicationRegistration
[D] unknown:0 - Wagnis::handleRegisterApplicationFinished
[D] unknown:0 - Wagnis::handleRegisterApplicationFinished
[D] unknown:0 - Wagnis::validateRegistrationData
[D] unknown:0 - [Wagnis] Payload:  "{\"id\":\"37de-c965-15ca-fdc8\",\"application\":\"harbour-zaster\",\"timestamp\":\"2018-11-28 09:26:07\",\"features\":[[],[]]}"
[D] unknown:0 - [Wagnis] Signature:  "n63jxR142TD+7WWW5OZrcxih0mrRHOZ0DHnbKXzBO7CdCzmSaOT2tpOrMGUonnVv5vQPu+/3ZbupfrYioPyz14UU5fsgc7z8JQqiq+GdEM5FxsuSIAaPxft522b1qHY4Gtd98sT8vb0WLoMECpYwhGTTRRLlNt71qzcA4bAPmTpH90ys72K6f3xwHaLjSv0R8hOxbT6d2qnIBkyrABcYsCuVckN6O+YxKUfrWTFHCCR6rSFqmt+7o20zrzBixaWNfe9f44+EfvfNq9qmbNFbmuWq09uFNe3xBx7//Vrd7wwZS2wjQu7shrFZ8NWbumEeybgrEKFhI+iJvl+BDfcJVg=="
[D] unknown:0 - [Wagnis] ID verified!
[D] unknown:0 - Wagnis::isSignatureValid
[D] unknown:0 - [Wagnis] Registration valid!
[D] unknown:0 - Wagnis::hasFeature "contribution"
[D] unknown:0 - Wagnis::inTestingPeriod
[D] unknown:0 - Wagnis::getRemainingTime
[D] unknown:0 - FinTsDialog::searchInstitute "50050201"
[D] unknown:0 - FinTsDialog::handleInstitutesSearchCompleted "50050201"
[D] onClicked:116 - Selected: Frankfurter Sparkasse, 50050201, https://banking-hs6.s-fints-pt-hs.de/fints30
[D] unknown:0 - FinTsDialog::initializeParameters
[D] unknown:0 - FinTsDialog::synchronization
[D] unknown:0 - FinTsDialog::createMessageSynchronization
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKIDN" "3" "2"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKVVB" "4" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKSYN" "5" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHA" "6" "2"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBS" "7" "1"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSK" "998" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSD" "999" "1"
[D] unknown:0 - FinTsDialog::handleSynchronizationFinished
[D] unknown:0 - FinTsDialog::parseReplyDialogInitialization
[D] unknown:0 - [FinTsDialog] Bank told us to use dialog ID "333551874900=408902514681CK3K="
[D] unknown:0 - FinTsDialog::parseReplyDialogInitialization
[D] unknown:0 - [FinTsDialog] Feedback for message:  "3060" "Bitte beachten Sie die enthaltenen Warnungen/Hinweise."
[D] unknown:0 - [FinTsDialog] Feedback for segment  "5" : "0020" "Auftrag ausgeführt."
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "3050" "BPD nicht mehr aktuell, aktuelle Version enthalten."
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "3920" "Zugelassene Zwei-Schritt-Verfahren für den Benutzer."
[D] unknown:0 - [FinTsDialog] Bank told us to use PIN/TAN method:  "910"
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "0020" "Der Auftrag wurde ausgeführt.(MBT62220100807)"
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "3938" "Ihr Zugang ist vorläufig gesperrt - Bitte PIN-Sperre aufheben."
[D] unknown:0 - [FinTsDialog] Bank Parameter Data (BPD) Version:  "1"
[D] unknown:0 - [FinTsDialog] Bank country code:  "280"
[D] unknown:0 - [FinTsDialog] Bank ID:  "50050201"
[D] unknown:0 - [FinTsDialog] Bank name:  "Frankfurter Sparkasse"
[D] unknown:0 - [FinTsDialog] Maximum transactions per message:  "3"
[D] unknown:0 - [FinTsDialog] Supported Language (0: Default, 1: German, 2: English, 3: French):  "1"
[D] unknown:0 - [FinTsDialog] Supported HBCI version:  "300"
[D] unknown:0 - [FinTsDialog] Supported security procedure:  "DDV" "1"
[D] unknown:0 - [FinTsDialog] Supported security procedure:  "RAH" "7"
[D] unknown:0 - [FinTsDialog] Supported security procedure:  "PIN" "1"
[D] unknown:0 - [FinTsDialog] PIN/TAN explicitly supported:  true
[D] unknown:0 - [FinTsDialog] Bank supports transactions message version:  4
[D] unknown:0 - [FinTsDialog] Bank supports transactions message version:  5
[D] unknown:0 - [FinTsDialog] Bank supports account balance message version:  3
[D] unknown:0 - [FinTsDialog] Bank supports account balance message version:  4
[D] unknown:0 - [FinTsDialog] Bank supports account balance message version:  5
[D] unknown:0 - [FinTsDialog] Bank supports portfolio info message version:  3
[D] unknown:0 - [FinTsDialog] Bank supports portfolio info message version:  5
[D] unknown:0 - [FinTsDialog] One-step PIN/TAN supported:  "J"
[D] unknown:0 - [FinTsDialog] One-step PIN/TAN supported:  "J"
[D] unknown:0 - [FinTsDialog] PIN/TAN implicitly supported by PIN/TAN information segment
[D] unknown:0 - [FinTsDialog] New Customer System ID:  "YHpAy05RWWcBAAA0/V2pqlcXrAQA"
[D] unknown:0 - FinTsDialog::closeDialog
[D] unknown:0 - FinTsDialog::createMessageCloseDialog
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKEND" "3" "1"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHA" "4" "2"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBS" "5" "1"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSK" "998" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSD" "999" "1"
[D] unknown:0 - FinTsDialog::handleDialogEndFinished
[D] unknown:0 - FinTsDialog::parseReplyCloseDialog
[D] unknown:0 - FinTsDialog::parseReplyCloseDialog
[D] unknown:0 - [FinTsDialog] Feedback for message:  "0010" "Nachricht entgegengenommen."
[D] unknown:0 - [FinTsDialog] Feedback for message:  "0100" "Dialog beendet."
[D] unknown:0 - FinTsBalances::retrieveBalances
[D] unknown:0 - FinTsBalances::setWorkInProgress true
[D] unknown:0 - FinTsDialog::dialogInitialization
[D] unknown:0 - Wagnis::hasFeature "contribution"
[D] unknown:0 - Wagnis::getRemainingTime
[D] unknown:0 - FinTsDialog::createMessageDialogInitialization
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKIDN" "3" "2"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKVVB" "4" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHA" "5" "2"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBS" "6" "1"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSK" "998" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNVSD" "999" "1"
[D] unknown:0 - FinTsDialog::handleDialogInitializationFinished
[D] unknown:0 - FinTsDialog::parseReplyDialogInitialization
[D] unknown:0 - [FinTsDialog] Bank told us to use dialog ID "395344024670=526012514681CK3K="
[D] unknown:0 - FinTsDialog::parseReplyDialogInitialization
[D] unknown:0 - [FinTsDialog] Feedback for message:  "3060" "Bitte beachten Sie die enthaltenen Warnungen/Hinweise."
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "3920" "Zugelassene Zwei-Schritt-Verfahren für den Benutzer."
[D] unknown:0 - [FinTsDialog] Bank told us to use PIN/TAN method:  "910"
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "0020" "Der Auftrag wurde ausgeführt.(MBT62220100807)"
[D] unknown:0 - [FinTsDialog] Feedback for segment  "4" : "3938" "Ihr Zugang ist vorläufig gesperrt - Bitte PIN-Sperre aufheben."
[D] unknown:0 - [FinTsDialog] Using account balance message version  5
[D] unknown:0 - [FinTsDialog] Using transactions message version  5
[D] unknown:0 - [FinTsDialog] Using portfolio info message version  5
[D] unknown:0 - [FinTsDialog] Dialog initialization completed
[D] unknown:0 - FinTsDialog::storeParameterData
[D] unknown:0 - FinTsDialog::accountBalance ""
[D] unknown:0 - FinTsDialog::createMessageAccountBalance ""
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNHBK" "1" "3"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HNSHK" "2" "4"
[D] unknown:0 - FinTsDialog::createSegmentHeader "HKSAL" "3" "5"
Speicherzugriffsfehler
