### ISSUE TITLE
Bank Account could be added twice.

### ISSUE THREAD

**Issue by andywuest** [Wunderfitz/harbour-zaster#7]
Hi, 

somehow i was able to add the bank account twice. See attached screenshot. I think that is not intended and should be prevented. When i switch back to the homescreen with all the open apps i can see in the cover view, that there are also the bank accounts twice. 

![zaster_bank_account_shows_up_twice](https://user-images.githubusercontent.com/644248/49250278-ba80ce80-f41e-11e8-9f24-ff2f75c0ba4f.png)

* Another strange thing is that when i tip on the cover view to open the app again, the onscreen keyboard is immediately displayed, even though it does not make sense to me if i already entered a bank account. The only way to get rid of the keyboard is to submit via the enter button. Also when i switch to the transactions and go back, the keyboard immediately shows up (i do not even see an input field for the keyboard.

* How can i remove the bank account to switch to another one? I would like to test another of my bank accounts. I think it would be nice if there would a pully menu entry that allows me to remove the currently entered bank account.

**Comment by Wunderfitz** [comment]
Mhmm, seems that something is completely messed up. No idea how to reproduce this, so I would recommend removing the settings file from /home/nemo/.config/harbour-zaster/finTsSettings.conf and setup the bank account again.

Switching/removing the bank account will be done in a later version of the app...

**Comment by andywuest** [comment]
I think you can close this one, as it is no longer relevant, due to the multibanking support.

**Comment by Wunderfitz** [comment]
Thanks for the feedback, closing this one then.
